export const INGREDIENT_CREATION_STARTED = 'INGREDIENT_CREATION_STARTED'
export const INGREDIENT_CREATION_SUCCEEDED = 'INGREDIENT_CREATION_SUCCEEDED'
export const INGREDIENT_CREATION_FAILED = 'INGREDIENT_CREATION_FAILED'

export const INGREDIENT_EDIT_STARTED = 'INGREDIENT_EDIT_STARTED'
export const INGREDIENT_EDIT_SUCCEEDED = 'INGREDIENT_EDIT_SUCCEEDED'
export const INGREDIENT_EDIT_FAILED = 'INGREDIENT_EDIT_FAILED'

export const INGREDIENT_DELETION_STARTED = 'INGREDIENT_DELETION_STARTED'
export const INGREDIENT_DELETION_SUCCEEDED = 'INGREDIENT_DELETION_SUCCEEDED'
export const INGREDIENT_DELETION_FAILED = 'INGREDIENT_DELETION_FAILED'

export const INGREDIENTS_FETCH_STARTED = 'INGREDIENTS_FETCH_STARTED'
export const INGREDIENTS_FETCH_SUCCEEDED = 'INGREDIENTS_FETCH_SUCCEEDED'
export const INGREDIENTS_FETCH_FAILED = 'INGREDIENTS_FETCH_FAILED'

export const SINGLE_JOKE_FETCH_STARTED = 'SINGLE_JOKE_FETCH_STARTED'
export const SINGLE_JOKE_FETCH_SUCCEEDED = 'SINGLE_JOKE_FETCH_SUCCEEDED'
export const SINGLE_JOKE_FETCH_FAILED = 'SINGLE_JOKE_FETCH_FAILED'

export const SALAD_CREATION_STARTED = 'SALAD_CREATION_STARTED'
export const SALAD_CREATION_SUCCEEDED = 'SALAD_CREATION_SUCCEEDED'
export const SALAD_CREATION_FAILED = 'SALAD_CREATION_FAILED'

export const SALADS_FETCH_STARTED = 'SALADS_FETCH_STARTED'
export const SALADS_FETCH_SUCCEEDED = 'SALADS_FETCH_SUCCEEDED'
export const SALADS_FETCH_FAILED = 'SALADS_FETCH_FAILED'
